### ISSUE TITLE
how is this different from the others around

### ISSUE THREAD

**Issue by ppjogani** [miguelantonio/storm-esper-bolt#4]
hey! I came across this on google search. Seems pretty similar to https://github.com/tomdz/storm-esper.
Any comments ?

**Comment by miguelantonio** [comment]
Hi @waater, this project is different from tomdz's because his implementation uses descriptors and this does not (this is just one Class), this uses simpler Maps to describe the Bolt input and output. Another difference is that this implementation allows SODA queries that are typesafe

Also, tomdz's project was the inspiration if this, I studied it and it is a very good starting point

Best regards!
